### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Pronjaboy** [bbarreto/sinesp-api#6]
Estou recebendo este erro, tanto no Digital Ocean quanto no Heroku. No localhost, funciona. Sabe dizer o que é?

**Comment by bbarreto** [comment]
O Sinesp bloqueia conexões de fora do país. Para usar, recomendo encapsular
como uma função lambda ou rodar em uma instância ec2 na AWS na região
sa-east-1.

Em 28 de ago de 2017 9:34 PM, "Tiago Borges" <notifications@github.com>
escreveu:

Estou recebendo este erro, tanto no Digital Ocean quanto no Heroku. No
localhost, funciona. Sabe dizer o que é?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bbarreto/sinesp-api/issues/6>, or mute the thread

**Comment by bbarreto** [comment]
@Pronjaboy conseguiu fazer funcionar?

**Comment by olivermathe** [comment]
Boa noite, estou tendo o mesmo problema, poderia explicar como posso resolver?
Minha aplicação esta no heroku.

**Comment by bbarreto** [comment]
@olivermathe O SINESP só aceita conexões a partir de servidores com IPs brasileiros. Hoje, o Heroku não possui nenhuma região no Brasil, então será necessário usar algum tipo de proxy ou utilizar outro serviço de hospedagem que possua servidores nacionais.

**Comment by olivermathe** [comment]
Criei uma instância ec2 na AWS na região sa-east-1 (FREE), o IP inicial não venho no "padrão" brasileiro ou seja, dentro da faixa de ips designados para o Brasil, então usei o Elastic IP da amazon para mudar o Ip. 

Abs...
